#!/usr/bin/env bash

scripts/symlink_dotfiles
sudo xcodebuild -license accept
brew upgrade
brew bundle
scripts/install_ruby.sh
scripts/install_node.sh
scripts/install_packages.sh
scripts/install_fonts.sh
scripts/configure_macos.sh
