function rm() {
  rm-ruby $@
}

DOTFILES_DIRECTORY="$(dirname $(dirname $(readlink ${BASH_SOURCE})))"

PATH="./node_modules/.bin:$PATH"
PATH="./bin:$PATH"
PATH="$DOTFILES_DIRECTORY/bin:$PATH"

source "$(brew --prefix asdf)/asdf.sh"

. /usr/local/etc/bash_completion.d/git-completion.bash

export EDITOR="atom --wait"
export GIT_EDITOR="atom --wait"

# General
alias ls="ls -G"

# Bundler
alias bc="bundle check"
alias be="bundle exec"
alias bi="bundle install"
alias bo="bundle outdated"
alias bu="bundle update"

# Rails
alias rc="rails console"
alias rs="rails server"

# Miscellaneous
alias av="aversion ~/Code"
alias e="atom"
alias dots="atom ~/Code/dotfiles"
alias pr="hub pull-request"
alias reload=". ~/.bash_profile"

source $DOTFILES_DIRECTORY/extras/prompt.bash
