eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(starship init zsh)"

DOTFILES_DIRECTORY=$(dirname $(dirname $(readlink ${(%):-%x})))
source $DOTFILES_DIRECTORY/config/aliases

PATH="./node_modules/.bin:$PATH"
PATH="./bin:$PATH"
PATH="$DOTFILES_DIRECTORY/bin:$PATH"

. $(brew --prefix asdf)/libexec/asdf.sh

# export EDITOR="code --wait"
# export GIT_EDITOR="code --wait"

function rm() {
	rm-ruby $@
}
