#!/usr/bin/env bash

current_directory=$(cd "$(dirname $(dirname "${BASH_SOURCE[0]}"))" && pwd)

for filename in $current_directory/atom/*; do
  echo "ln -sf $filename AND ~/.atom/$(basename $filename)"
done

for filename in $current_directory/home/*; do
  echo "ln -sf $filename AND ~/.$(basename $filename)"
done
