#!/usr/bin/env ruby

require "fileutils"

dotfiles_directory = File.dirname(__dir__)

def files_in(directory_name)
  dotfiles_directory = File.dirname(__dir__)
  Dir.glob("#{dotfiles_directory}/#{directory_name}/**/*").reverse
end

def log(from, to)
  puts "Symlink #{from.sub(Dir.home, '~')} to #{to}"
end

files_in("home").each do |to|
  relative_to = to.sub("#{dotfiles_directory}/home/", "")
  from = "#{Dir.home}/.#{relative_to}"

  log(from, to)
  FileUtils.symlink(to, from, force: true)
end

puts

files_in("atom").each do |to|
  relative_to = to.sub("#{dotfiles_directory}/atom/", "")
  from = "#{Dir.home}/.atom/#{relative_to}"

  log(from, to)
  FileUtils.symlink(to, from, force: true)
end

puts

files_in("vscode").each do |to|
  relative_to = to.sub("#{dotfiles_directory}/vscode/", "")
  from = "#{Dir.home}/Library/Application\ Support/Code/User/#{relative_to}"

  log(from, to)
  FileUtils.symlink(to, from, force: true)
end
